SSUT-485: Placeholder homepages
hmrc/safety-and-security-entry-declaration-frontend pull request #114
Opened 2022-04-19 13:40 UTC by AdamCoops

2022-04-19 15:58 UTC, giftig requested changes
A few suggestions

2022-04-19 15:58 UTC, giftig commented on app/controllers/declarations/DraftDeclarationsController.scala
> +    (identify).async { implicit request =>
You can ditch the brackets around `identify` since it's just the one step

2022-04-19 15:58 UTC, giftig commented on app/controllers/declarations/DraftDeclarationsController.scala
> +      lrns.map { ids =>
If you ditch the `lrns` val it probably reads better, since you can then use `lrns` instead of `ids` in the map

2022-04-19 15:58 UTC, giftig commented on app/repositories/SessionRepository.scala
> +        .find(byUserId(userId)).map {l => l.lrn}
Might be better to call this `list` or `summaryList` since we know it'll probably change to include more than just LRN when we flesh out the drafts page, and we'd have to rename it then. Fundamentally this method aims to list some info of our draft declarations, rather than specifically being able getting IDs only.

2022-04-19 15:58 UTC, giftig commented on app/viewmodels/declarations/DraftDeclarationsSummary.scala
> +    (implicit messages: Messages): SummaryListRow = {
you should wrap at the brackets if you need to wrap, so like

```
def row(localReferenceNumber: LocalReferenceNumber)(
  implicit messages: Messages
): SummaryListRow = {
```

though to be fair if you abbreviated your argument to `lrn` it'll probably go on one line just fine.

2022-04-19 15:58 UTC, giftig commented on it/repositories/SessionRepositorySpec.scala
> +    "When there are draft declarations will return their lrns" - {
Pedantic but lowercase `w` to match other test cases

2022-04-19 15:58 UTC, giftig commented on it/repositories/SessionRepositorySpec.scala
> +      refs.foreach { lrn => insert(userAnswers1.copy(lrn = lrn)).futureValue }
It'd be better to use `Future.traverse` like the second snippet I showed you; we'll save some time by inserting the different sets of answers in parallel rather than one at a time.

```scala
Future.traverse(refs) { lrn => insert(userAnswers1.copy(lrn = lrn)) }.futureValue
```

2022-04-19 15:58 UTC, giftig commented on it/repositories/SessionRepositorySpec.scala
> +      val refs: List[LocalReferenceNumber] = {
Nick used a simpler approach of just providing some static lrns and answers on the spec when he made his bugfix earlier, so you may as well just use those, I think. I'd suggest tweaking the names a bit, making your own `lrn3` + `userAnswers3`, changing Nick's `userAnswers3` to something like `userAnswers1Updated` to better represent what he was testing, and then you can just use your 3 sets of answers here.

2022-04-19 15:58 UTC, giftig commented on it/repositories/SessionRepositorySpec.scala
> +    }
So just to clarify with my two suggestions above the whole thing will probably look more like:

```scala
val answers = Seq(userAnswers1, userAnswers2, userAnswers3)
val expected = Seq(lrn1, lrn2, lrn3)

Future.traverse(answers)(insert).futureValue

val actual = repository.getLrns(userId1).futureValue
actual must contain theSameElementsAs(expected)
```

2022-04-19 16:09 UTC, AdamCoops commented on app/controllers/declarations/DraftDeclarationsController.scala
> +      lrns.map { ids =>
as in do :

repository.getLrns(request.userId).map { xyzzy

2022-04-20 09:58 UTC, giftig commented on it/repositories/SessionRepositorySpec.scala
> +      val answers = Seq(userAnswers1, userAnswers2, userAnswers3)
You're not using answers here. You can simplify your traverse by just using answers, though you'll have to update `userAnswers3` the way I suggested, changing the existing one to a new name. I think that would be much clearer so it's worth doing imo.

2022-04-20 12:10 UTC, giftig requested changes
One small remaining thing, not sure if I missed that in the first pass.

2022-04-20 12:10 UTC, giftig commented on app/controllers/declarations/DraftDeclarationsController.scala
> +    }
these lines are all overindented

2022-04-20 13:07 UTC, merged