SSUT-326: GoodsItem Model + Extractor + Spec
hmrc/safety-and-security-entry-declaration-frontend pull request #129
Opened 2022-05-03 12:08 UTC by PerrettJ4

Implemented goods item extractor and goods item model including spec.

2022-05-03 13:23 UTC, giftig requested changes
Some comments

2022-05-03 13:23 UTC, giftig commented on app/extractors/ValidationError.scala
> +  case object MissingQueryResult extends ValidationError{
We've generally dealt with queries returning no results by blaming it on the first page which should have been filled out in order for the query to return some answers.

In this case we can say `MissingField(CommodityCodeKnownPage(Index(0)))`

2022-05-03 13:23 UTC, giftig commented on app/models/completion/answers/GoodsItem.scala
> +import models.{Container, Document, PaymentMethod}
These should be imported before `models.completion` (capital letters before lowercase)

2022-05-03 13:23 UTC, giftig commented on app/models/completion/answers/RouteDetails.scala
> +
You've changed some whitespace here and added a (presumably unused?) import here, looks like you'll want to check this file back out from main.

2022-05-03 13:23 UTC, giftig commented on app/queries/Query.scala
> -
Same thing here

2022-05-03 13:23 UTC, giftig commented on app/queries/goods/AllDocumentsQuery.scala
> -
And here

2022-05-03 13:23 UTC, giftig commented on hs_err_pid80900.log
> +#
You've committed some JVM panic log files, please remove these.

2022-05-03 13:23 UTC, giftig commented on test-utils/utils/RouteDetailsUtils.scala
> +trait RouteDetailsUtils {
Neither of these utils seem to be in use anywhere in the end, so let's ditch this trait.

2022-05-03 13:23 UTC, giftig commented on test-utils/utils/PartiesUtils.scala
> +  def tradersToParties(traders: List[Trader]): Map[Int, Party] = {
Looks like you've moved this from being a private def on `PartiesExtractorSpec`, but that's the only place this util has been used, so we should move it back and ditch the trait.

2022-05-03 13:23 UTC, giftig commented on test/extractors/RouteDetailsExtractorSpec.scala
> +val routeDetails = arbitrary[RouteDetails].sample.get
Looks like this file should be checked out from main, this change seems accidental.

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +  }
Can you move this to after the arbitrary values it depends on? These have technically worked ok because the vals are lazy, but can cause some confusing compiler errors in some scenarios; to rely on an implicit you will need to already have it in scope (i.e. have defined it first)

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +  implicit lazy val arbitraryStandardPackageItem : Arbitrary[StandardPackageItem] = Arbitrary {
Extra space before the colon here

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +    //TODO check if mark or number is optional or not.
Is this TODO still relevant? If you think the model might need to change, let's raise a ticket to investigate.

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +      mapLoadingPlace <- listOfPlaces.zipWithIndex.map{ case(a,b) => (b,a) }.toMap
Several missing spaces here; before the open brace, after `case`, after both commas.

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +      length <- Gen.choose(min,max)
Missing space after comma

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +    implicit val max = 10
A few things here:

1. these should not be implicit; if anything here actually took an implicit `Int` they'd immediately complain you've defined two contradictory implicit `Int`s. An implicit of such a common type should also be avoided regardless, since it leads to confusing behaviour.
2. We're ok with just having directly-set min and max values for our `choose`s here; they vary a bit depending on individual needs so setting vals at all for these imply they should be consistent values which isn't true.
3. We'd like to try to avoid generating too much data as it's led to a slow down in tests previously, so sticking to something like 1-3 would be ideal; 1-10 may be too many when you consider we have lists within lists and these counts will get multiplied.

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +      placesOfUnloading <- genPlaceOfLoading  // TODO update when UnloadingPlace fixed
TODO no longer relevant here

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +    val genPlaceOfLoading = for {
This implies it's singular but it's multiple, as a map.

Be careful with wording too, since we have `PlaceOfLoading` and `LoadingPlace` as different models, so it may get confusing. An explicit type annotation may be helpful here.

2022-05-03 13:23 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +      listOfPlaces <- Gen.listOfN(length, arbitrary[LoadingPlace])
Avoid names like `listOfPlaces` or `mapLoadingPlace`, as they are examples of Systems Hungarian notation, where the name indicates the data type, rather than expressing the meaningful content.

For example, `loadingPlaces` and `loadingPlacesByIndex` would be more informative names (or drop the "loading" to make it more concise)

2022-05-03 13:30 UTC, giftig commented on hs_err_pid80900.log
> +#
Probably an idea to add `*.log` to the `.gitignore` too to avoid this next time.

2022-05-03 14:35 UTC, PerrettJ4 commented on app/extractors/ValidationError.scala
> +  case object MissingQueryResult extends ValidationError{
something like?
case object MissingQueryResult extends ValidationError{
    override val message: String = MissingField(CommodityCodeKnownPage(Index(0)))
  }

2022-05-03 15:50 UTC, salman-a-dev commented on test-utils/generators/ModelGenerators.scala
> +    //TODO check if mark or number is optional or not.
I will raise a ticket for this.

2022-05-03 16:09 UTC, giftig commented on app/extractors/ValidationError.scala
> +  case object MissingQueryResult extends ValidationError{
No, just get rid of `MissingQueryResult` and use `MissingField(CommodityCodeKnownPage(Index(0)))` as your reported error.

2022-05-04 10:21 UTC, giftig reviewed
Looks good, just a couple of very small points remaining.

2022-05-04 10:21 UTC, giftig commented on test/extractors/GoodsItemExtractorSpec.scala
>    private val grossMass = 1000
I notice you wrap this in `BigDecimal.exact` when you set the answer, and you've also copied the 1000 magic number in your new `expectedGrossMass`. Probably you should just wrap it in the `BigDecimal.exact` here, and you can then set L61 to `Some(grossMass)`

2022-05-04 10:21 UTC, giftig commented on test/extractors/GoodsItemsExtractorSpec.scala
> +import pages.goods.{AnyShippingContainersPage}
You can ditch the braces here

2022-05-04 10:53 UTC, giftig approved these changes

2022-05-04 11:00 UTC, merged