SSUT-522: Refactored WithTraders to use a GBEori rather than a string…
hmrc/safety-and-security-entry-declaration-frontend pull request #131
Opened 2022-05-04 15:19 UTC by AdamCoops

…. removed unused imports

2022-05-04 16:22 UTC, giftig requested changes

2022-05-04 16:22 UTC, giftig commented on app/models/Trader.scala
> +  override val displayName: String = eori.toString
You've changed the way this is displayed; currently it's going to be written as `GbEori(123451234512)` whereas before it would have been `GB123451234512`. The `displayName` is used on the radio button pages for parties in the goods item section, so take a look at those pages to confirm you don't change the behaviour there.

Easiest way to resolve this is to override `toString` on `GbEori` (or else add a `displayName` parameter to it to be more specific)

2022-05-04 16:22 UTC, giftig commented on app/viewmodels/checkAnswers/consignees/AddConsigneeSummary.scala
> +          case t: TraderWithEori    => HtmlFormat.escape(t.eori.toString).toString
Feels like we should just be using `name.displayName` here instead of this match, might be worth checking if you can simplify this since you're touching it; you should be able to check what this looks like on the parties check your answers page. The same applies to all the other similar matches.

If this is doing more than it seems and I'm missing some subtle logic here let me know, but I think that should just work.

2022-05-04 16:22 UTC, giftig commented on test-utils/generators/ModelGenerators.scala
> +      } yield TraderWithEori(key, GbEori(eori.value))
just use `eori`; you're taking the string value from a generated `GbEori` and putting it back into a new `GbEori` right now.

2022-05-04 16:22 UTC, giftig commented on test/controllers/goods/ConsigneeControllerSpec.scala
> +    TraderWithEori(key2, GbEori(eori2.value))
same here and in the next several files, just use `eori1` and `eori2`

2022-05-04 16:22 UTC, giftig commented on test/models/TraderSpec.scala
> +      val trader: Trader = TraderWithEori(123, GbEori("GB123456789000"))
We skip the GB prefix when we read data into `GbEori`, so to make this look like "correct" test data we should use `GbEori("123456789000")` instead.

2022-05-04 16:22 UTC, giftig commented on test/viewmodels/checkAnswers/goods/ConsigneeSummarySpec.scala
> +    val consignee1 = TraderWithEori(1, GbEori(arbitrary[GbEori].sample.value.toString))
Again all you need here is `arbitrary[GbEori].sample.value`

2022-05-05 12:49 UTC, giftig commented on app/models/Trader.scala
> +  override val displayName: String = eori.toString
Yeah the value is just the digits, so you'd want something like a `displayName` which puts that back on to show to the user.

2022-05-05 12:51 UTC, AdamCoops commented on app/models/Trader.scala
> +  override val displayName: String = eori.toString
override val displayName: String = "GB" + eori.value?

2022-05-05 12:54 UTC, giftig commented on app/models/Trader.scala
> +  override val displayName: String = eori.toString
Well I meant adding a display name to the `GbEori` model probably makes sense, and then here you could just use `eori.displayName`. That way you have a display format  for the user wherever you have a GB EORI, and the details of how to display that makes most sense in `GbEori` rather than in one type which contains a `GbEori`.

2022-05-05 13:29 UTC, giftig approved these changes

2022-05-05 14:10 UTC, merged