Implemented Autocomplete and updated frontend and tests for Nationali…
hmrc/safety-and-security-entry-declaration-frontend pull request #60
Opened 2022-03-10 15:17 UTC by AdamCoops

…tyOfTransport

2022-03-10 16:20 UTC, versatil56 requested changes
Did we run the tests before creating this PR? Please have a look at it as checks are failing.

2022-03-10 17:22 UTC, giftig reviewed
Minor points about style

2022-03-10 17:22 UTC, giftig commented on app/forms/transport/NationalityOfTransportFormProvider.scala
> +import models.Country.allCountries
Generally you should avoid importing vals rather than the objects, so I'd rather you just refer to it as `Country.allCountries` below.

2022-03-10 17:22 UTC, giftig commented on app/pages/transport/NationalityOfTransportPage.scala
> +}
Kind of trivial point here but you've removed a blank line from the end of the file, which github is marking here. Git considers this worth warning about, because it will mess up your terminal if you cat it, and prevent files being correctly concatenated, etc.

2022-03-10 17:22 UTC, giftig commented on app/views/transport/NationalityOfTransportView.scala.html
> +@import models.Country._
Here too, preferably just import `Country`

2022-03-10 17:22 UTC, giftig commented on conf/messages.en
> +nationalityOfTransport.error.length = The Nationality must be 100 characters or less
Is this message even used anymore?

2022-03-10 17:22 UTC, giftig commented on test/pages/transport/NationalityOfTransportPageSpec.scala
> +            .onPageLoad(NormalMode, emptyUserAnswers.lrn))
This way of wrapping is a little hard to read and the trailing bracket makes it hard to see how they match. Scalafmt would fix this, or you can do it manually. It should look more like

```scala.mustEqual(
  transportRoutes.RoroUnaccompaniedIdentityController
    .onPageLoad(NormalMode, emptyUserAnswers.lrn)
)


```

2022-03-10 17:25 UTC, giftig commented on app/pages/transport/NationalityOfTransportPage.scala
> +}
Incidentally you can configure intellij to make sure these are put in: https://stackoverflow.com/questions/16761227/how-to-make-intellij-idea-insert-a-new-line-at-every-end-of-file

2022-03-10 17:47 UTC, AdamCoops commented on app/views/transport/NationalityOfTransportView.scala.html
> +@import models.Country._
So Referencing Country.AllCountries breaks the view. I need to look into this.

2022-03-10 17:49 UTC, giftig commented on app/views/transport/NationalityOfTransportView.scala.html
> +@import models.Country._
silly question but was that just a typo here? it's defined as `Country.allCountries`, lowercase. I'm not very familiar with twirl but I hope it can't mess up something as simple as this.

2022-03-11 09:10 UTC, giftig commented on test/pages/transport/NationalityOfTransportPageSpec.scala
> +            .onPageLoad(NormalMode, emptyUserAnswers.lrn))
the `.onPageLoad` is still underindented, should be indented from the previous line since it's operating on it.

2022-03-11 09:27 UTC, giftig approved these changes

2022-03-11 10:56 UTC, merged